### ISSUE TITLE
Can I use this?

### ISSUE THREAD

**Issue by remotevase** [Ad5001/Elytra#2]
Can I implement the main features of this plugin into TesseractTeam/Tesseract and H4PM/Elywing?

**Comment by Ad5001** [comment]
Hum... that wouldn't be a great idea because the plugin would become mostly uselessfor the 2 days I spent to create it.

**Comment by remotevase** [comment]
Oh... Well I wouldn't add it to genisys or pocketmine, just the minor two (tesseract and Elywing)

**Comment by remotevase** [comment]
Sorry,  but I will anyways... Although I did not get your personal consent, the license states that I can use it anyways because I am making technical modifications.

> The Licensor waives and/or agrees not to assert any right or authority to forbid You from making technical modifications necessary to exercise the Licensed Rights, including technical modifications necessary to circumvent Effective Technological Measures

**Comment by Ad5001** [comment]
Read the whole license:
> Section 3 – License Conditions.

Your exercise of the Licensed Rights is expressly made subject to the following conditions.

Attribution.

If You Share the Licensed Material (including in modified form), You must:

retain the following if it is supplied by the Licensor with the Licensed Material:
identification of the creator(s) of the Licensed Material and any others designated to receive attribution, in any reasonable manner requested by the Licensor (including by pseudonym if designated);
a copyright notice;
a notice that refers to this Public License;
a notice that refers to the disclaimer of warranties;
a URI or hyperlink to the Licensed Material to the extent reasonably practicable;
indicate if You modified the Licensed Material and retain an indication of any previous modifications; and
indicate the Licensed Material is licensed under this Public License, and include the text of, or the URI or hyperlink to, this Public License.
You may satisfy the conditions in Section 3(a)(1) in any reasonable manner based on the medium, means, and context in which You Share the Licensed Material. For example, it may be reasonable to satisfy the conditions by providing a URI or hyperlink to a resource that includes the required information.
If requested by the Licensor, You must remove any of the information required by Section 3(a)(1)(A) to the extent reasonably practicable.
ShareAlike.
In addition to the conditions in Section 3(a), if You Share Adapted Material You produce, the following conditions also apply.

The Adapter’s License You apply must be a Creative Commons license with the same License Elements, this version or later, or a BY-NC-SA Compatible License.
You must include the text of, or the URI or hyperlink to, the Adapter's License You apply. You may satisfy this condition in any reasonable manner based on the medium, means, and context in which You Share Adapted Material.
You may not offer or impose any additional or different terms or conditions on, or apply any Effective Technological Measures to, Adapted Material that restrict exercise of the rights granted under the Adapter's License You apply.

**Comment by remotevase** [comment]
Oops... Sorry, now I cant use it :( Oh well
